---
- name: Configurazione di Rocky Linux 9
  hosts: all
  become: true

  tasks:
    # Aggiorna i pacchetti
    - name: Aggiorna tutti i pacchetti
      yum:
        name: "*"
        state: latest

    # Installa i prerequisiti per Docker CE
    - name: Installa pacchetti necessari
      yum:
        name:
          - yum-utils
          - device-mapper-persistent-data
          - lvm2
          - python3-pip
        state: present

    # Installa la libreria Python 'requests'
    - name: Installa il modulo Python 'requests'
      pip:
        name: requests
        executable: pip3

    # Aggiungi il repository Docker CE
    - name: Aggiungi il repository Docker CE
      command: >
        yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

    # Installa Docker CE
    - name: Installa Docker CE
      yum:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present

    # Abilita e avvia il servizio Docker
    - name: Abilita e avvia il servizio Docker
      systemd:
        name: docker
        enabled: true
        state: started

    # Creazione del volume Docker per Jenkins
    - name: Crea il volume Docker per Jenkins
      docker_volume:
        name: jenkins_home

    # Creazione della rete Docker per Jenkins
    - name: Creazione di una rete Docker personalizzata
      docker_network:
        name: jenkins_network
        driver: bridge
        ipam_config:
          - subnet: "172.20.0.0/16"

    # Configurazione del container Jenkins Master
    - name: Esegui il container Jenkins Master
      docker_container:
        name: jenkins_master
        image: jenkins/jenkins:lts
        state: started
        restart_policy: always
        user: root
        networks:
          - name: jenkins_network
            ipv4_address: 172.20.0.2  # IP statico per il Master
        ports:
          - "8080:8080"
          - "50000:50000"

    # Configurazione del container Jenkins Slave (con accesso Docker)
    - name: Esegui il container Jenkins Slave
      docker_container:
        name: jenkins_slave
        image: jenkins/inbound-agent
        state: started
        restart_policy: always
        user: root
        networks:
          - name: jenkins_network
            ipv4_address: 172.20.0.3  # IP statico per lo Slave
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock  # Monta il socket Docker per l'accesso al Docker Host
          - jenkins_home:/var/jenkins_home           # Volume per persistenza dati
        env:
          JENKINS_URL: http://172.20.0.2:8080
          JENKINS_AGENT_NAME: "slave"
          JENKINS_AGENT_WORKDIR: "/home/jenkins"
          JENKINS_SECRET: "jenkins_secret"  # Sostituisci con la chiave segreta del Master

    # Installazione di K3s
    - name: Installa K3s
      shell: |
        curl -sfL https://get.k3s.io | sh -
      args:
        creates: /usr/local/bin/k3s

    # Verifica che K3s sia stato installato correttamente
    - name: Verifica l'installazione di K3s
      command: k3s --version

    # Creazione del namespace 'formazione-sou' in K3s
    - name: Crea il namespace 'formazione-sou'
      command: kubectl create namespace formazione-sou
      become_user: root
      environment:
        KUBEVIRT_KUBEVIRT_KUBECTL: "/usr/local/bin/k3s kubectl"
