apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-reader-binding
  labels:
    app: flask-app-example
subjects:
  - kind: ServiceAccount
    name: cluster-reader-sa
    namespace: formazione-sou
roleRef:
  kind: ClusterRole
  name: cluster-reader
  apiGroup: rbac.authorization.k8s.io
